import type { FormItem, Defect, User } from "./types";

const today = new Date();
const daysAgo = (n: number) => new Date(today.getTime() - n * 86400000).toISOString();

export const seedUsers: User[] = [
  { id: "u-1", name: "Saisrija", email: "saisrija@zenwork.com", role: "admin", active: true },
  { id: "u-2", name: "Arun Kumar", email: "arun@zenwork.com", role: "agent", active: true },
  { id: "u-3", name: "Priya Sharma", email: "priya@zenwork.com", role: "agent", active: true },
  { id: "u-4", name: "Ravi Teja", email: "ravi@zenwork.com", role: "agent", active: true },
];

const f = (
  id: string,
  name: string,
  module: FormItem["module"],
  status: FormItem["status"],
  passed: number,
  failed: number,
  openDefects: number,
  daysOld: number,
  agent: string,
): FormItem => ({
  id,
  name,
  module,
  status,
  passed,
  failed,
  openDefects,
  lastTested: daysAgo(daysOld),
  assignedAgent: agent,
});

export const seedForms: FormItem[] = [
  // 1099 Forms
  f("1099-NEC", "Form 1099-NEC", "1099 Forms", "Passed", 240, 5, 0, 1, "Arun Kumar"),
  f("1099-MISC", "Form 1099-MISC", "1099 Forms", "Passed", 198, 4, 0, 2, "Priya Sharma"),
  f("1099-INT", "Form 1099-INT", "1099 Forms", "Passed", 156, 3, 1, 3, "Arun Kumar"),
  f("1099-K", "Form 1099-K", "1099 Forms", "In Progress", 120, 12, 4, 1, "Ravi Teja"),
  f("1099-DIV", "Form 1099-DIV", "1099 Forms", "Passed", 132, 2, 0, 4, "Priya Sharma"),
  f("1099-R", "Form 1099-R", "1099 Forms", "Open Bug", 88, 9, 3, 2, "Arun Kumar"),
  f("1099-S", "Form 1099-S", "1099 Forms", "Passed", 70, 1, 0, 5, "Ravi Teja"),
  f("1099-PATR", "Form 1099-PATR", "1099 Forms", "Pending", 0, 0, 0, 0, "Priya Sharma"),
  f("1099-B", "Form 1099-B", "1099 Forms", "Passed", 110, 6, 1, 3, "Arun Kumar"),
  f("1099-C", "Form 1099-C", "1099 Forms", "Retest Required", 64, 4, 2, 2, "Ravi Teja"),
  f("1099-OID", "Form 1099-OID", "1099 Forms", "Passed", 52, 1, 0, 6, "Priya Sharma"),
  f("1099-A", "Form 1099-A", "1099 Forms", "Passed", 48, 0, 0, 7, "Arun Kumar"),
  f("1099-SA", "Form 1099-SA", "1099 Forms", "In Progress", 30, 5, 2, 1, "Ravi Teja"),
  f("1099-Q", "Form 1099-Q", "1099 Forms", "Passed", 44, 1, 0, 4, "Priya Sharma"),
  f("1099-G", "Form 1099-G", "1099 Forms", "Passed", 80, 2, 0, 5, "Arun Kumar"),
  f("1099-DA", "Form 1099-DA", "1099 Forms", "Pending", 0, 0, 0, 0, "Priya Sharma"),
  f("1099-HC", "Form 1099-HC", "1099 Forms", "Open Bug", 35, 7, 2, 1, "Ravi Teja"),
  f("1099-LS", "Form 1099-LS", "1099 Forms", "Passed", 28, 0, 0, 8, "Arun Kumar"),
  f("1097-BTC", "Form 1097-BTC", "1099 Forms", "Passed", 24, 1, 0, 6, "Priya Sharma"),
  f("1099-QA", "Form 1099-QA", "1099 Forms", "Passed", 22, 0, 0, 9, "Arun Kumar"),
  // 990 Forms
  f("990", "Form 990", "990 Forms", "Passed", 95, 3, 1, 2, "Priya Sharma"),
  f("990-N", "Form 990-N", "990 Forms", "Passed", 60, 1, 0, 4, "Arun Kumar"),
  f("990-T", "Form 990-T", "990 Forms", "Open Bug", 42, 5, 2, 1, "Ravi Teja"),
  f("990-PF", "Form 990-PF", "990 Forms", "Passed", 38, 1, 0, 5, "Priya Sharma"),
  f("990-EZ", "Form 990-EZ", "990 Forms", "In Progress", 50, 4, 1, 1, "Arun Kumar"),
  // Integrations
  f("INT-QB", "QuickBooks Integration", "Integrations", "Passed", 80, 2, 0, 2, "Arun Kumar"),
  f("INT-XR", "Xero Integration", "Integrations", "Passed", 65, 1, 0, 3, "Priya Sharma"),
  f("INT-ST", "Stripe Integration", "Integrations", "In Progress", 48, 6, 2, 1, "Ravi Teja"),
  f("INT-SF", "Salesforce Integration", "Integrations", "Open Bug", 35, 8, 3, 1, "Arun Kumar"),
  f("INT-GD", "Google Drive Integration", "Integrations", "Passed", 28, 1, 0, 4, "Priya Sharma"),
  f("INT-AUTH", "API Authentication", "Integrations", "Passed", 110, 3, 0, 2, "Ravi Teja"),
  f("INT-BULK", "Bulk Upload API", "Integrations", "Retest Required", 55, 5, 2, 1, "Arun Kumar"),
  f("INT-EFILE", "E-file API", "Integrations", "Passed", 90, 2, 0, 3, "Priya Sharma"),
  // 1099 Online
  f("OL-LOGIN", "Portal Login Testing", "1099 Online", "Passed", 40, 1, 0, 2, "Arun Kumar"),
  f("OL-CREATE", "Form Creation Testing", "1099 Online", "In Progress", 65, 7, 2, 1, "Ravi Teja"),
  f("OL-BULK", "Bulk Upload Testing", "1099 Online", "Open Bug", 30, 5, 2, 1, "Priya Sharma"),
  f("OL-PAY", "Payment Flow Testing", "1099 Online", "Passed", 48, 2, 0, 3, "Arun Kumar"),
  f("OL-EFILE", "E-filing Flow Testing", "1099 Online", "Passed", 55, 1, 0, 2, "Ravi Teja"),
  f("OL-DASH", "Dashboard Testing", "1099 Online", "Passed", 38, 0, 0, 4, "Priya Sharma"),
  f(
    "OL-PDF",
    "PDF Generation Testing",
    "1099 Online",
    "Retest Required",
    25,
    3,
    1,
    1,
    "Arun Kumar",
  ),
  f("OL-EMAIL", "Email Notification Testing", "1099 Online", "Passed", 22, 1, 0, 5, "Ravi Teja"),
];

export const seedDefects: Defect[] = [
  {
    id: "DEF-1001",
    module: "1099 Forms",
    formFeature: "Form 1099-R",
    title: "Recipient TIN validation accepts invalid format",
    description: "TIN field accepts non-numeric characters and lets the form submit.",
    stepsToReproduce: "1. Open 1099-R\n2. Enter TIN with letters\n3. Submit",
    expectedResult: "Validation error shown",
    actualResult: "Form submits successfully",
    status: "In Progress",
    priority: "High",
    severity: "High",
    assignedAgent: "Arun Kumar",
    createdBy: "Arun Kumar",
    updatedBy: "Arun Kumar",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    comments: [],
    jiraUrl: "https://jira.example.com/ZEN-1001",
  },
  {
    id: "DEF-1002",
    module: "Integrations",
    formFeature: "Salesforce Integration",
    title: "Token refresh fails after 24 hours",
    description: "OAuth token does not auto-refresh and API returns 401.",
    stepsToReproduce: "1. Authorize Salesforce\n2. Wait 24h\n3. Trigger sync",
    expectedResult: "Token auto-refreshes silently",
    actualResult: "401 Unauthorized returned",
    status: "Reported",
    priority: "Critical",
    severity: "Critical",
    assignedAgent: "Ravi Teja",
    createdBy: "Priya Sharma",
    updatedBy: "Priya Sharma",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    comments: [],
  },
  {
    id: "DEF-1003",
    module: "1099 Online",
    formFeature: "Bulk Upload Testing",
    title: "CSV upload truncates rows beyond 5000",
    description: "Large CSV files lose rows silently with no error.",
    stepsToReproduce: "1. Upload CSV with 6000 rows\n2. Check imported count",
    expectedResult: "All 6000 rows imported",
    actualResult: "Only 5000 rows imported",
    status: "Ongoing",
    priority: "High",
    severity: "Medium",
    assignedAgent: "Priya Sharma",
    createdBy: "Ravi Teja",
    updatedBy: "Ravi Teja",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
    comments: [],
  },
  {
    id: "DEF-1004",
    module: "990 Forms",
    formFeature: "Form 990-T",
    title: "Schedule A calculation rounding error",
    description: "Totals off by $1 due to rounding at each line item.",
    stepsToReproduce: "1. Enter Schedule A items\n2. Compare totals",
    expectedResult: "Exact total",
    actualResult: "$1 discrepancy",
    status: "Fixed",
    priority: "Medium",
    severity: "Low",
    assignedAgent: "Ravi Teja",
    createdBy: "Arun Kumar",
    updatedBy: "Ravi Teja",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(2),
    comments: [],
  },
  {
    id: "DEF-1005",
    module: "1099 Forms",
    formFeature: "Form 1099-HC",
    title: "Print preview misaligned in landscape",
    description: "Header overlaps body text in landscape print preview.",
    stepsToReproduce: "1. Open 1099-HC\n2. Print preview landscape",
    expectedResult: "Clean layout",
    actualResult: "Header overlaps content",
    status: "Reopened",
    priority: "Medium",
    severity: "Medium",
    assignedAgent: "Arun Kumar",
    createdBy: "Saisrija",
    updatedBy: "Saisrija",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
    comments: [],
  },
  {
    id: "DEF-1006",
    module: "1099 Online",
    formFeature: "PDF Generation Testing",
    title: "Generated PDF missing watermark on draft",
    description: "Draft PDFs should include the DRAFT watermark.",
    stepsToReproduce: "1. Save form as draft\n2. Download PDF",
    expectedResult: "DRAFT watermark visible",
    actualResult: "No watermark",
    status: "Retest Required",
    priority: "Low",
    severity: "Low",
    assignedAgent: "Priya Sharma",
    createdBy: "Arun Kumar",
    updatedBy: "Priya Sharma",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
    comments: [],
  },
];
