/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppZenworkPaymentsRouteImport } from './routes/_app.zenwork-payments'
import { Route as AppTax1099FeaturesRouteImport } from './routes/_app.tax1099-features'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSelectEnvironmentRouteImport } from './routes/_app.select-environment'
import { Route as AppRetestRouteImport } from './routes/_app.retest'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOnline1099RouteImport } from './routes/_app.online-1099'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppMyReportedErrorsRouteImport } from './routes/_app.my-reported-errors'
import { Route as AppMyErrorsRouteImport } from './routes/_app.my-errors'
import { Route as AppKnowledgeBaseRouteImport } from './routes/_app.knowledge-base'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppFunctionalityTestingRouteImport } from './routes/_app.functionality-testing'
import { Route as AppFormsRouteImport } from './routes/_app.forms'
import { Route as AppExcelImportTestingRouteImport } from './routes/_app.excel-import-testing'
import { Route as AppDefectsRouteImport } from './routes/_app.defects'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatbotTestingRouteImport } from './routes/_app.chatbot-testing'
import { Route as AppAdminRouteImport } from './routes/_app._admin'
import { Route as App990FormsRouteImport } from './routes/_app.990-forms'
import { Route as App2290FormsRouteImport } from './routes/_app.2290-forms'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as ApiPublicAppVersionRouteImport } from './routes/api/public/app-version'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app.tasks.$taskId'
import { Route as AppAdminRightsManagementRouteImport } from './routes/_app._admin.rights-management'
import { Route as AppAdminReportsRouteImport } from './routes/_app._admin.reports'
import { Route as AppAdminRealtimeDebugRouteImport } from './routes/_app._admin.realtime-debug'
import { Route as AppAdminAuthEventsRouteImport } from './routes/_app._admin.auth-events'
import { Route as AppAdminAuditLogRouteImport } from './routes/_app._admin.audit-log'
import { Route as AppAdminAgentsRouteImport } from './routes/_app._admin.agents'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppZenworkPaymentsRoute = AppZenworkPaymentsRouteImport.update({
  id: '/zenwork-payments',
  path: '/zenwork-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppTax1099FeaturesRoute = AppTax1099FeaturesRouteImport.update({
  id: '/tax1099-features',
  path: '/tax1099-features',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSelectEnvironmentRoute = AppSelectEnvironmentRouteImport.update({
  id: '/select-environment',
  path: '/select-environment',
  getParentRoute: () => AppRoute,
} as any)
const AppRetestRoute = AppRetestRouteImport.update({
  id: '/retest',
  path: '/retest',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnline1099Route = AppOnline1099RouteImport.update({
  id: '/online-1099',
  path: '/online-1099',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMyReportedErrorsRoute = AppMyReportedErrorsRouteImport.update({
  id: '/my-reported-errors',
  path: '/my-reported-errors',
  getParentRoute: () => AppRoute,
} as any)
const AppMyErrorsRoute = AppMyErrorsRouteImport.update({
  id: '/my-errors',
  path: '/my-errors',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseRoute = AppKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFunctionalityTestingRoute = AppFunctionalityTestingRouteImport.update({
  id: '/functionality-testing',
  path: '/functionality-testing',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppExcelImportTestingRoute = AppExcelImportTestingRouteImport.update({
  id: '/excel-import-testing',
  path: '/excel-import-testing',
  getParentRoute: () => AppRoute,
} as any)
const AppDefectsRoute = AppDefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotTestingRoute = AppChatbotTestingRouteImport.update({
  id: '/chatbot-testing',
  path: '/chatbot-testing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const App990FormsRoute = App990FormsRouteImport.update({
  id: '/990-forms',
  path: '/990-forms',
  getParentRoute: () => AppRoute,
} as any)
const App2290FormsRoute = App2290FormsRouteImport.update({
  id: '/2290-forms',
  path: '/2290-forms',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppVersionRoute = ApiPublicAppVersionRouteImport.update({
  id: '/api/public/app-version',
  path: '/api/public/app-version',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRightsManagementRoute =
  AppAdminRightsManagementRouteImport.update({
    id: '/rights-management',
    path: '/rights-management',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRealtimeDebugRoute = AppAdminRealtimeDebugRouteImport.update({
  id: '/realtime-debug',
  path: '/realtime-debug',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuthEventsRoute = AppAdminAuthEventsRouteImport.update({
  id: '/auth-events',
  path: '/auth-events',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditLogRoute = AppAdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAgentsRoute = AppAdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/2290-forms': typeof App2290FormsRoute
  '/990-forms': typeof App990FormsRoute
  '/chatbot-testing': typeof AppChatbotTestingRoute
  '/dashboard': typeof AppDashboardRoute
  '/defects': typeof AppDefectsRoute
  '/excel-import-testing': typeof AppExcelImportTestingRoute
  '/forms': typeof AppFormsRoute
  '/functionality-testing': typeof AppFunctionalityTestingRoute
  '/integrations': typeof AppIntegrationsRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/my-errors': typeof AppMyErrorsRoute
  '/my-reported-errors': typeof AppMyReportedErrorsRoute
  '/notes': typeof AppNotesRoute
  '/notifications': typeof AppNotificationsRoute
  '/online-1099': typeof AppOnline1099Route
  '/profile': typeof AppProfileRoute
  '/retest': typeof AppRetestRoute
  '/select-environment': typeof AppSelectEnvironmentRoute
  '/settings': typeof AppSettingsRoute
  '/tax1099-features': typeof AppTax1099FeaturesRoute
  '/zenwork-payments': typeof AppZenworkPaymentsRoute
  '/agents': typeof AppAdminAgentsRoute
  '/audit-log': typeof AppAdminAuditLogRoute
  '/auth-events': typeof AppAdminAuthEventsRoute
  '/realtime-debug': typeof AppAdminRealtimeDebugRoute
  '/reports': typeof AppAdminReportsRoute
  '/rights-management': typeof AppAdminRightsManagementRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/2290-forms': typeof App2290FormsRoute
  '/990-forms': typeof App990FormsRoute
  '/chatbot-testing': typeof AppChatbotTestingRoute
  '/dashboard': typeof AppDashboardRoute
  '/defects': typeof AppDefectsRoute
  '/excel-import-testing': typeof AppExcelImportTestingRoute
  '/forms': typeof AppFormsRoute
  '/functionality-testing': typeof AppFunctionalityTestingRoute
  '/integrations': typeof AppIntegrationsRoute
  '/knowledge-base': typeof AppKnowledgeBaseRoute
  '/my-errors': typeof AppMyErrorsRoute
  '/my-reported-errors': typeof AppMyReportedErrorsRoute
  '/notes': typeof AppNotesRoute
  '/notifications': typeof AppNotificationsRoute
  '/online-1099': typeof AppOnline1099Route
  '/profile': typeof AppProfileRoute
  '/retest': typeof AppRetestRoute
  '/select-environment': typeof AppSelectEnvironmentRoute
  '/settings': typeof AppSettingsRoute
  '/tax1099-features': typeof AppTax1099FeaturesRoute
  '/zenwork-payments': typeof AppZenworkPaymentsRoute
  '/agents': typeof AppAdminAgentsRoute
  '/audit-log': typeof AppAdminAuditLogRoute
  '/auth-events': typeof AppAdminAuthEventsRoute
  '/realtime-debug': typeof AppAdminRealtimeDebugRoute
  '/reports': typeof AppAdminReportsRoute
  '/rights-management': typeof AppAdminRightsManagementRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/2290-forms': typeof App2290FormsRoute
  '/_app/990-forms': typeof App990FormsRoute
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/chatbot-testing': typeof AppChatbotTestingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/defects': typeof AppDefectsRoute
  '/_app/excel-import-testing': typeof AppExcelImportTestingRoute
  '/_app/forms': typeof AppFormsRoute
  '/_app/functionality-testing': typeof AppFunctionalityTestingRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/knowledge-base': typeof AppKnowledgeBaseRoute
  '/_app/my-errors': typeof AppMyErrorsRoute
  '/_app/my-reported-errors': typeof AppMyReportedErrorsRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/online-1099': typeof AppOnline1099Route
  '/_app/profile': typeof AppProfileRoute
  '/_app/retest': typeof AppRetestRoute
  '/_app/select-environment': typeof AppSelectEnvironmentRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tax1099-features': typeof AppTax1099FeaturesRoute
  '/_app/zenwork-payments': typeof AppZenworkPaymentsRoute
  '/_app/_admin/agents': typeof AppAdminAgentsRoute
  '/_app/_admin/audit-log': typeof AppAdminAuditLogRoute
  '/_app/_admin/auth-events': typeof AppAdminAuthEventsRoute
  '/_app/_admin/realtime-debug': typeof AppAdminRealtimeDebugRoute
  '/_app/_admin/reports': typeof AppAdminReportsRoute
  '/_app/_admin/rights-management': typeof AppAdminRightsManagementRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/api/public/app-version': typeof ApiPublicAppVersionRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/2290-forms'
    | '/990-forms'
    | '/chatbot-testing'
    | '/dashboard'
    | '/defects'
    | '/excel-import-testing'
    | '/forms'
    | '/functionality-testing'
    | '/integrations'
    | '/knowledge-base'
    | '/my-errors'
    | '/my-reported-errors'
    | '/notes'
    | '/notifications'
    | '/online-1099'
    | '/profile'
    | '/retest'
    | '/select-environment'
    | '/settings'
    | '/tax1099-features'
    | '/zenwork-payments'
    | '/agents'
    | '/audit-log'
    | '/auth-events'
    | '/realtime-debug'
    | '/reports'
    | '/rights-management'
    | '/tasks/$taskId'
    | '/api/public/app-version'
    | '/api/public/manifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/2290-forms'
    | '/990-forms'
    | '/chatbot-testing'
    | '/dashboard'
    | '/defects'
    | '/excel-import-testing'
    | '/forms'
    | '/functionality-testing'
    | '/integrations'
    | '/knowledge-base'
    | '/my-errors'
    | '/my-reported-errors'
    | '/notes'
    | '/notifications'
    | '/online-1099'
    | '/profile'
    | '/retest'
    | '/select-environment'
    | '/settings'
    | '/tax1099-features'
    | '/zenwork-payments'
    | '/agents'
    | '/audit-log'
    | '/auth-events'
    | '/realtime-debug'
    | '/reports'
    | '/rights-management'
    | '/tasks/$taskId'
    | '/api/public/app-version'
    | '/api/public/manifest'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/2290-forms'
    | '/_app/990-forms'
    | '/_app/_admin'
    | '/_app/chatbot-testing'
    | '/_app/dashboard'
    | '/_app/defects'
    | '/_app/excel-import-testing'
    | '/_app/forms'
    | '/_app/functionality-testing'
    | '/_app/integrations'
    | '/_app/knowledge-base'
    | '/_app/my-errors'
    | '/_app/my-reported-errors'
    | '/_app/notes'
    | '/_app/notifications'
    | '/_app/online-1099'
    | '/_app/profile'
    | '/_app/retest'
    | '/_app/select-environment'
    | '/_app/settings'
    | '/_app/tax1099-features'
    | '/_app/zenwork-payments'
    | '/_app/_admin/agents'
    | '/_app/_admin/audit-log'
    | '/_app/_admin/auth-events'
    | '/_app/_admin/realtime-debug'
    | '/_app/_admin/reports'
    | '/_app/_admin/rights-management'
    | '/_app/tasks/$taskId'
    | '/api/public/app-version'
    | '/api/public/manifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicAppVersionRoute: typeof ApiPublicAppVersionRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/zenwork-payments': {
      id: '/_app/zenwork-payments'
      path: '/zenwork-payments'
      fullPath: '/zenwork-payments'
      preLoaderRoute: typeof AppZenworkPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tax1099-features': {
      id: '/_app/tax1099-features'
      path: '/tax1099-features'
      fullPath: '/tax1099-features'
      preLoaderRoute: typeof AppTax1099FeaturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/select-environment': {
      id: '/_app/select-environment'
      path: '/select-environment'
      fullPath: '/select-environment'
      preLoaderRoute: typeof AppSelectEnvironmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/retest': {
      id: '/_app/retest'
      path: '/retest'
      fullPath: '/retest'
      preLoaderRoute: typeof AppRetestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/online-1099': {
      id: '/_app/online-1099'
      path: '/online-1099'
      fullPath: '/online-1099'
      preLoaderRoute: typeof AppOnline1099RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-reported-errors': {
      id: '/_app/my-reported-errors'
      path: '/my-reported-errors'
      fullPath: '/my-reported-errors'
      preLoaderRoute: typeof AppMyReportedErrorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-errors': {
      id: '/_app/my-errors'
      path: '/my-errors'
      fullPath: '/my-errors'
      preLoaderRoute: typeof AppMyErrorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/functionality-testing': {
      id: '/_app/functionality-testing'
      path: '/functionality-testing'
      fullPath: '/functionality-testing'
      preLoaderRoute: typeof AppFunctionalityTestingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/excel-import-testing': {
      id: '/_app/excel-import-testing'
      path: '/excel-import-testing'
      fullPath: '/excel-import-testing'
      preLoaderRoute: typeof AppExcelImportTestingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/defects': {
      id: '/_app/defects'
      path: '/defects'
      fullPath: '/defects'
      preLoaderRoute: typeof AppDefectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chatbot-testing': {
      id: '/_app/chatbot-testing'
      path: '/chatbot-testing'
      fullPath: '/chatbot-testing'
      preLoaderRoute: typeof AppChatbotTestingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/990-forms': {
      id: '/_app/990-forms'
      path: '/990-forms'
      fullPath: '/990-forms'
      preLoaderRoute: typeof App990FormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/2290-forms': {
      id: '/_app/2290-forms'
      path: '/2290-forms'
      fullPath: '/2290-forms'
      preLoaderRoute: typeof App2290FormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-version': {
      id: '/api/public/app-version'
      path: '/api/public/app-version'
      fullPath: '/api/public/app-version'
      preLoaderRoute: typeof ApiPublicAppVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin/rights-management': {
      id: '/_app/_admin/rights-management'
      path: '/rights-management'
      fullPath: '/rights-management'
      preLoaderRoute: typeof AppAdminRightsManagementRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/reports': {
      id: '/_app/_admin/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/realtime-debug': {
      id: '/_app/_admin/realtime-debug'
      path: '/realtime-debug'
      fullPath: '/realtime-debug'
      preLoaderRoute: typeof AppAdminRealtimeDebugRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/auth-events': {
      id: '/_app/_admin/auth-events'
      path: '/auth-events'
      fullPath: '/auth-events'
      preLoaderRoute: typeof AppAdminAuthEventsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/audit-log': {
      id: '/_app/_admin/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAdminAuditLogRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/agents': {
      id: '/_app/_admin/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAdminAgentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAgentsRoute: typeof AppAdminAgentsRoute
  AppAdminAuditLogRoute: typeof AppAdminAuditLogRoute
  AppAdminAuthEventsRoute: typeof AppAdminAuthEventsRoute
  AppAdminRealtimeDebugRoute: typeof AppAdminRealtimeDebugRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminRightsManagementRoute: typeof AppAdminRightsManagementRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAgentsRoute: AppAdminAgentsRoute,
  AppAdminAuditLogRoute: AppAdminAuditLogRoute,
  AppAdminAuthEventsRoute: AppAdminAuthEventsRoute,
  AppAdminRealtimeDebugRoute: AppAdminRealtimeDebugRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminRightsManagementRoute: AppAdminRightsManagementRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  App2290FormsRoute: typeof App2290FormsRoute
  App990FormsRoute: typeof App990FormsRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppChatbotTestingRoute: typeof AppChatbotTestingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDefectsRoute: typeof AppDefectsRoute
  AppExcelImportTestingRoute: typeof AppExcelImportTestingRoute
  AppFormsRoute: typeof AppFormsRoute
  AppFunctionalityTestingRoute: typeof AppFunctionalityTestingRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppKnowledgeBaseRoute: typeof AppKnowledgeBaseRoute
  AppMyErrorsRoute: typeof AppMyErrorsRoute
  AppMyReportedErrorsRoute: typeof AppMyReportedErrorsRoute
  AppNotesRoute: typeof AppNotesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnline1099Route: typeof AppOnline1099Route
  AppProfileRoute: typeof AppProfileRoute
  AppRetestRoute: typeof AppRetestRoute
  AppSelectEnvironmentRoute: typeof AppSelectEnvironmentRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTax1099FeaturesRoute: typeof AppTax1099FeaturesRoute
  AppZenworkPaymentsRoute: typeof AppZenworkPaymentsRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  App2290FormsRoute: App2290FormsRoute,
  App990FormsRoute: App990FormsRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppChatbotTestingRoute: AppChatbotTestingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDefectsRoute: AppDefectsRoute,
  AppExcelImportTestingRoute: AppExcelImportTestingRoute,
  AppFormsRoute: AppFormsRoute,
  AppFunctionalityTestingRoute: AppFunctionalityTestingRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppKnowledgeBaseRoute: AppKnowledgeBaseRoute,
  AppMyErrorsRoute: AppMyErrorsRoute,
  AppMyReportedErrorsRoute: AppMyReportedErrorsRoute,
  AppNotesRoute: AppNotesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnline1099Route: AppOnline1099Route,
  AppProfileRoute: AppProfileRoute,
  AppRetestRoute: AppRetestRoute,
  AppSelectEnvironmentRoute: AppSelectEnvironmentRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTax1099FeaturesRoute: AppTax1099FeaturesRoute,
  AppZenworkPaymentsRoute: AppZenworkPaymentsRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicAppVersionRoute: ApiPublicAppVersionRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
